/* Automatically generated by
	VMPluginCodeGenerator * VMMaker.oscog-EstebanLorenzano.1881 uuid: ed616067-a57c-409b-bfb6-dab51f058235
   from
	AndroidPlugin * VMMaker.oscog-EstebanLorenzano.1881 uuid: ed616067-a57c-409b-bfb6-dab51f058235
 */
static char __buildInfo[] = "AndroidPlugin * VMMaker.oscog-EstebanLorenzano.1881 uuid: ed616067-a57c-409b-bfb6-dab51f058235 " __DATE__ ;



#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <jni.h>

/* Default EXPORT macro that does nothing (see comment in sq.h): */
#define EXPORT(returnType) returnType

/* Do not include the entire sq.h file but just those parts needed. */
#include "sqConfig.h"			/* Configuration options */
#include "sqVirtualMachine.h"	/*  The virtual machine proxy definition */
#include "sqPlatformSpecific.h"	/* Platform specific definitions */

#define true 1
#define false 0
#define null 0  /* using 'null' because nil is predefined in Think C */
#ifdef SQUEAK_BUILTIN_PLUGIN
# undef EXPORT
# define EXPORT(returnType) static returnType
#endif

#include "sqMemoryAccess.h"


/*** Function Prototypes ***/
EXPORT(const char*) getModuleName(void);
EXPORT(sqInt) primBriefMessage(void);
EXPORT(sqInt) primInAndroid(void);
EXPORT(sqInt) primSetPitch(void);
EXPORT(sqInt) primSetSpeechRate(void);
EXPORT(sqInt) primShortCut(void);
EXPORT(sqInt) primSpeak(void);
EXPORT(sqInt) setInterpreter(struct VirtualMachine*anInterpreter);
static void * stringArgumentAt(sqInt anOffset);


/*** Variables ***/

#if !defined(SQUEAK_BUILTIN_PLUGIN)
static sqInt (*byteSizeOf)(sqInt oop);
static void * (*firstIndexableField)(sqInt oop);
static sqInt (*isBytes)(sqInt oop);
static sqInt (*pop)(sqInt nItems);
static sqInt (*primitiveFail)(void);
static sqInt (*pushBool)(sqInt trueOrFalse);
static sqInt (*pushInteger)(sqInt integerValue);
static double (*stackFloatValue)(sqInt offset);
static sqInt (*stackIntegerValue)(sqInt offset);
static sqInt (*stackValue)(sqInt offset);
#else /* !defined(SQUEAK_BUILTIN_PLUGIN) */
extern sqInt byteSizeOf(sqInt oop);
extern void * firstIndexableField(sqInt oop);
extern sqInt isBytes(sqInt oop);
extern sqInt pop(sqInt nItems);
extern sqInt primitiveFail(void);
extern sqInt pushBool(sqInt trueOrFalse);
extern sqInt pushInteger(sqInt integerValue);
extern double stackFloatValue(sqInt offset);
extern sqInt stackIntegerValue(sqInt offset);
extern sqInt stackValue(sqInt offset);
extern
#endif
struct VirtualMachine* interpreterProxy;
static const char *moduleName =
#ifdef SQUEAK_BUILTIN_PLUGIN
	"AndroidPlugin * VMMaker.oscog-EstebanLorenzano.1881 (i)"
#else
	"AndroidPlugin * VMMaker.oscog-EstebanLorenzano.1881 (e)"
#endif
;



/*	Note: This is hardcoded so it can be run from Squeak.
	The module name is used for validating a module *after*
	it is loaded to check if it does really contain the module
	we're thinking it contains. This is important! */

	/* InterpreterPlugin>>#getModuleName */
EXPORT(const char*)
getModuleName(void)
{
	return moduleName;
}

	/* AndroidPlugin>>#primBriefMessage */
EXPORT(sqInt)
primBriefMessage(void)
{
    void *alc;
    jmethodID bmmeth;
    sqInt index;
    jstring jmsg;
    char *msg;
    sqInt pointer;
    sqInt size;
    jclass vmcls;
    jobject vmobj;

	/* begin stringArgumentAt: */
	pointer = stackValue(0);
	if (!(isBytes(pointer))) {
		msg = ((void *) (primitiveFail()));
		goto l1;
	}
	index = firstIndexableField(pointer);
	size = byteSizeOf(pointer);
	alc = alloca(size + 1);
	memset(alc, 0, size + 1);
	memcpy(alc, index, size);
	msg = alc;
l1:	/* end stringArgumentAt: */;
	vmcls = getVMClass();
	if (!(vmcls)) {
return primitiveFail();
	}
	vmobj = getVMObject();
	if (!(vmobj)) {
return primitiveFail();
	}
	bmmeth = getMethodwithSiginClass("briefMessage", "(Ljava/lang/String;)V", vmcls);
	if (!(bmmeth)) {
return primitiveFail();
	}
	jmsg = asJavaString(msg);
	if (!(jmsg)) {
return primitiveFail();
	}
	callVoidMethodOnwith(bmmeth, vmobj, jmsg);
	pop(1);
	return 0;
}


/*	return true if running in Android. outside Android this primitive fails */

	/* AndroidPlugin>>#primInAndroid */
EXPORT(sqInt)
primInAndroid(void)
{
	pop(1);
	pushBool(1);
	return 0;
}

	/* AndroidPlugin>>#primSetPitch */
EXPORT(sqInt)
primSetPitch(void)
{
    jmethodID bmmeth;
    float pitch;
    sqInt res;
    jclass vmcls;
    jobject vmobj;

	pitch = stackFloatValue(0);
	vmcls = getVMClass();
	if (!(vmcls)) {
return primitiveFail();
	}
	vmobj = getVMObject();
	if (!(vmobj)) {
return primitiveFail();
	}
	bmmeth = getMethodwithSiginClass("setPitch", "(F)I", vmcls);
	if (!(bmmeth)) {
return primitiveFail();
	}
	res = callIntMethodOnwith(bmmeth, vmobj, pitch);
	pop(2);
	pushInteger(res);
	return 0;
}

	/* AndroidPlugin>>#primSetSpeechRate */
EXPORT(sqInt)
primSetSpeechRate(void)
{
    jmethodID bmmeth;
    float rate;
    sqInt res;
    jclass vmcls;
    jobject vmobj;

	rate = stackFloatValue(0);
	vmcls = getVMClass();
	if (!(vmcls)) {
return primitiveFail();
	}
	vmobj = getVMObject();
	if (!(vmobj)) {
return primitiveFail();
	}
	bmmeth = getMethodwithSiginClass("setSpeechRate", "(F)I", vmcls);
	if (!(bmmeth)) {
return primitiveFail();
	}
	res = callIntMethodOnwith(bmmeth, vmobj, rate);
	pop(2);
	pushInteger(res);
	return 0;
}


/*	path label cmd width height bits */

	/* AndroidPlugin>>#primShortCut */
EXPORT(sqInt)
primShortCut(void)
{
    void *alc;
    void *alc1;
    void *alc2;
    sqInt bitlen;
    sqInt bitptr;
    sqInt bits;
    void * cmd;
    sqInt height;
    void * imglabel;
    char *imgpath;
    sqInt index;
    sqInt index1;
    sqInt index2;
    sqInt jbits;
    sqInt jcmd;
    sqInt jlabel;
    jstring jpath;
    jmethodID meth;
    sqInt pointer;
    sqInt pointer1;
    sqInt pointer2;
    sqInt size;
    sqInt size1;
    sqInt size2;
    jclass vmcls;
    jobject vmobj;
    sqInt width;

	/* begin stringArgumentAt: */
	pointer = stackValue(5);
	if (!(isBytes(pointer))) {
		imgpath = ((void *) (primitiveFail()));
		goto l1;
	}
	index = firstIndexableField(pointer);
	size = byteSizeOf(pointer);
	alc = alloca(size + 1);
	memset(alc, 0, size + 1);
	memcpy(alc, index, size);
	imgpath = alc;
l1:	/* end stringArgumentAt: */;
	jpath = asJavaString(imgpath);
	if (!(jpath)) {
return primitiveFail();
	}
	/* begin stringArgumentAt: */
	pointer1 = stackValue(4);
	if (!(isBytes(pointer1))) {
		imglabel = primitiveFail();
		goto l2;
	}
	index1 = firstIndexableField(pointer1);
	size1 = byteSizeOf(pointer1);
	alc1 = alloca(size1 + 1);
	memset(alc1, 0, size1 + 1);
	memcpy(alc1, index1, size1);
	imglabel = alc1;
l2:	/* end stringArgumentAt: */;
	jlabel = asJavaString(imglabel);
	if (!(jlabel)) {
return primitiveFail();
	}
	/* begin stringArgumentAt: */
	pointer2 = stackValue(3);
	if (!(isBytes(pointer2))) {
		cmd = primitiveFail();
		goto l3;
	}
	index2 = firstIndexableField(pointer2);
	size2 = byteSizeOf(pointer2);
	alc2 = alloca(size2 + 1);
	memset(alc2, 0, size2 + 1);
	memcpy(alc2, index2, size2);
	cmd = alc2;
l3:	/* end stringArgumentAt: */;
	jcmd = asJavaString(cmd);
	if (!(jcmd)) {
return primitiveFail();
	}
	width = stackIntegerValue(2);
	height = stackIntegerValue(1);
	bits = stackValue(0);
	if (bits == null) {
jbits = null;
	}
	else {
if (!(isBytes(bits))) {
			return primitiveFail();
		}
		bitlen = byteSizeOf(bits);
		bitptr = firstIndexableField(bits);
		jbits = asJavaByteArray(bitptr, bitlen);
		if (!(jbits)) {
return primitiveFail();
		}
	}
	vmcls = getVMClass();
	if (!(vmcls)) {
return primitiveFail();
	}
	vmobj = getVMObject();
	if (!(vmobj)) {
return primitiveFail();
	}
	meth = getMethodwithSiginClass("imageShortCut", "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;II[B)V", vmcls);
	if (!(meth)) {
return primitiveFail();
	}
	callVoidMethodOnwithmanyargs(meth, vmobj, jpath, jlabel, jcmd, width, height, jbits);
	pop(6);
	return 0;
}

	/* AndroidPlugin>>#primSpeak */
EXPORT(sqInt)
primSpeak(void)
{
    void *alc;
    jmethodID bmmeth;
    sqInt index;
    jstring jmsg;
    char *msg;
    sqInt pointer;
    sqInt res;
    sqInt size;
    jclass vmcls;
    jobject vmobj;

	/* begin stringArgumentAt: */
	pointer = stackValue(0);
	if (!(isBytes(pointer))) {
		msg = ((void *) (primitiveFail()));
		goto l1;
	}
	index = firstIndexableField(pointer);
	size = byteSizeOf(pointer);
	alc = alloca(size + 1);
	memset(alc, 0, size + 1);
	memcpy(alc, index, size);
	msg = alc;
l1:	/* end stringArgumentAt: */;
	vmcls = getVMClass();
	if (!(vmcls)) {
return primitiveFail();
	}
	vmobj = getVMObject();
	if (!(vmobj)) {
return primitiveFail();
	}
	bmmeth = getMethodwithSiginClass("speak", "(Ljava/lang/String;)I", vmcls);
	if (!(bmmeth)) {
return primitiveFail();
	}
	jmsg = asJavaString(msg);
	if (!(jmsg)) {
return primitiveFail();
	}
	res = callIntMethodOnwith(bmmeth, vmobj, jmsg);
	pop(2);
	pushInteger(res);
	return 0;
}


/*	Note: This is coded so that it can be run in Squeak. */

	/* InterpreterPlugin>>#setInterpreter: */
EXPORT(sqInt)
setInterpreter(struct VirtualMachine*anInterpreter)
{
    sqInt ok;

	interpreterProxy = anInterpreter;
	ok = ((interpreterProxy->majorVersion()) == (VM_PROXY_MAJOR))
	 && ((interpreterProxy->minorVersion()) >= (VM_PROXY_MINOR));
	if (ok) {

#if !defined(SQUEAK_BUILTIN_PLUGIN)
		byteSizeOf = interpreterProxy->byteSizeOf;
		firstIndexableField = interpreterProxy->firstIndexableField;
		isBytes = interpreterProxy->isBytes;
		pop = interpreterProxy->pop;
		primitiveFail = interpreterProxy->primitiveFail;
		pushBool = interpreterProxy->pushBool;
		pushInteger = interpreterProxy->pushInteger;
		stackFloatValue = interpreterProxy->stackFloatValue;
		stackIntegerValue = interpreterProxy->stackIntegerValue;
		stackValue = interpreterProxy->stackValue;
#endif /* !defined(SQUEAK_BUILTIN_PLUGIN) */
	}
	return ok;
}


/*	To be inlined: common operations to obtain a string argument value at
	given stack offset.
	The string returned is null-terminated, and alloca-d, so will be freed
	automatically 
 */

	/* AndroidPlugin>>#stringArgumentAt: */
static void *
stringArgumentAt(sqInt anOffset)
{
    void *alc;
    sqInt index;
    sqInt pointer;
    sqInt size;

	pointer = stackValue(anOffset);
	if (!(isBytes(pointer))) {
		return primitiveFail();
	}
	index = firstIndexableField(pointer);
	size = byteSizeOf(pointer);
	alc = alloca(size + 1);
	memset(alc, 0, size + 1);
	memcpy(alc, index, size);
	return alc;
}


#ifdef SQUEAK_BUILTIN_PLUGIN

static char _m[] = "AndroidPlugin";
void* AndroidPlugin_exports[][3] = {
	{(void*)_m, "getModuleName", (void*)getModuleName},
	{(void*)_m, "primBriefMessage\000\001", (void*)primBriefMessage},
	{(void*)_m, "primInAndroid\000\377", (void*)primInAndroid},
	{(void*)_m, "primSetPitch\000\000", (void*)primSetPitch},
	{(void*)_m, "primSetSpeechRate\000\000", (void*)primSetSpeechRate},
	{(void*)_m, "primShortCut\000\001", (void*)primShortCut},
	{(void*)_m, "primSpeak\000\001", (void*)primSpeak},
	{(void*)_m, "setInterpreter", (void*)setInterpreter},
	{NULL, NULL, NULL}
};

#else /* ifdef SQ_BUILTIN_PLUGIN */

signed char primBriefMessageAccessorDepth = 1;
signed char primSetPitchAccessorDepth = 0;
signed char primSetSpeechRateAccessorDepth = 0;
signed char primShortCutAccessorDepth = 1;
signed char primSpeakAccessorDepth = 1;

#endif /* ifdef SQ_BUILTIN_PLUGIN */
